// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDIEbQlzwvDNc6wsJCKbLQP3-yTU-Mj4E',
    appId: '1:682676678047:web:fda9ffd44fca7bf5b6a1aa',
    messagingSenderId: '682676678047',
    projectId: 'dalel-5928e',
    authDomain: 'dalel-5928e.firebaseapp.com',
    storageBucket: 'dalel-5928e.firebasestorage.app',
    measurementId: 'G-50KBV8EZYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATXVLRHLWfgEvr0A--ILeeBsZw2ge-368',
    appId: '1:682676678047:android:656296c90c529833b6a1aa',
    messagingSenderId: '682676678047',
    projectId: 'dalel-5928e',
    storageBucket: 'dalel-5928e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsDYAHiDZVhUwgy1qB8YlXovltETqej5s',
    appId: '1:682676678047:ios:54028559664ca209b6a1aa',
    messagingSenderId: '682676678047',
    projectId: 'dalel-5928e',
    storageBucket: 'dalel-5928e.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsDYAHiDZVhUwgy1qB8YlXovltETqej5s',
    appId: '1:682676678047:ios:54028559664ca209b6a1aa',
    messagingSenderId: '682676678047',
    projectId: 'dalel-5928e',
    storageBucket: 'dalel-5928e.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDIEbQlzwvDNc6wsJCKbLQP3-yTU-Mj4E',
    appId: '1:682676678047:web:de144589a77f6b62b6a1aa',
    messagingSenderId: '682676678047',
    projectId: 'dalel-5928e',
    authDomain: 'dalel-5928e.firebaseapp.com',
    storageBucket: 'dalel-5928e.firebasestorage.app',
    measurementId: 'G-QQWDDG0W52',
  );
}
